name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    types: [synchronize]
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Compile
        run: make build
      - name: Test
        run: make test
